
export const sample_items: any[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Alandi'],
    stars: 4.5,
    imageUrl: 'assets/item-1.jpg',
    tags: ['FastRetail', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Manchurian',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['Dehuphata'],
    stars: 4.7,
    imageUrl: 'assets/item-2.jpg',
    tags: ['SlowRetail', 'Lunch'],
  },
  {
    id:'3',
    name: 'Burger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['Doodulgaon'],
    stars: 3.5,
    imageUrl: 'assets/item-3.jpg',
    tags: ['FastRetail', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fries',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['Alandi'],
    stars: 3.3,
    imageUrl: 'assets/item-4.jpg',
    tags: ['FastRetail', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/item-5.jpg',
    tags: ['Charholi'],
  },
  {
    id:'6',
    name: 'Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Dehu-phata'],
    stars: 4.0,
    imageUrl: 'assets/item-6.jpg',
    tags: ['FastRetail', 'Pizza', 'Lunch'],
  },
]

export const sample_tags:any[] = [
  { name: 'All', count: 6 },
  { name: 'FastRetail', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowRetail', count: 2 },
  { name: 'Burger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]

export const sample_users: any[] = [
  {
    name: "Prithvi",
    email: "prithvi@gmail.com",
    password: "123",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "Jane Doe",
    email: "Jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: false,
  },
];
